### ISSUE TITLE
Server-side intl not working (Next 15)

### ISSUE THREAD

**Issue by CarrettaRiccardo** [aymericzip/intlayer#103]
Hey! I like this i18n package ;)

I found an issue while trying to follow the basic implementation of translations for Nextjs 15.2
With the basic template: `[locale]/layout.tsx` and `[locale]/page.tsx`, using server-side `useIntlayer` throws an error **both with turbo on and off**.
(it works with client-side useIntlayer tho, when used inside a "use client" component)

[locale]/page.tsx
```tsx
import { type NextPageIntlayer } from "next-intlayer";
import { IntlayerServerProvider, useIntlayer } from "next-intlayer/server";

function PageContent() {
  const t = useIntlayer("page");

  return (
    <div>
      <p>{t.getStarted.main}</p>
    </div>
  );
}

const Page: NextPageIntlayer = async ({ params }) => {
  const { locale } = await params;

  return (
    <IntlayerServerProvider locale={locale}>
      <PageContent />
    </IntlayerServerProvider>
  );
};

export default Page;
```

[locale]/layout.tsx
```tsx
const LocaleLayout: NextLayoutIntlayer = async ({ children, params }) => {
  const { locale } = await params;

  return (
    <html
      lang={locale}
      dir={getHTMLTextDir(locale)}
    >
      <body
        className={cn(
          "min-h-screen w-screen bg-background font-sans antialiased motion-reduce:!transition-none",
          heading.variable,
          copy.variable,
        )}
      >
        <IntlayerClientProvider locale={locale}>
          {children}
        </IntlayerClientProvider>
      </body>
    </html>
  );
}

export default LocaleLayout;
```

---

I get the following error with Turbopack ON:

<img width="1042" alt="Image" src="https://github.com/user-attachments/assets/7556aec1-6cfe-43d1-b618-531123ecf281" />

<img width="520" alt="Image" src="https://github.com/user-attachments/assets/1ed69fb7-68c8-4525-a6c0-c415ebf25466" />

---

While i get the following error with Turbopack OFF (Webpack):

<img width="459" alt="Image" src="https://github.com/user-attachments/assets/7b475f2b-84cd-4415-bf16-8fdb42cdbc18" />

<img width="465" alt="Image" src="https://github.com/user-attachments/assets/01c0bb25-09e7-407f-83a1-cb0f732b248a" />

**Comment by aymericzip** [comment]
Hi @CarrettaRiccardo, thanks for your issue! 

Your code looks effectively correct. I will investigate. Maybe downgrading nextjs to 15.1.7 for now will fix it

**Comment by aymericzip** [comment]
Hey @CarrettaRiccardo,

I tested multiple versions of Next.js, and everything seems to work fine up to `v15.2.0`.  

- Versions >= `v15.2.0` return an error on `npm run start`:  
  _`TypeError: Cannot read properties of undefined (reading 'stack')`_. However, the application build works properly.  
- Versions >= `v15.2.1-canary.0` return an error during the build:  
  _`Cannot set properties of undefined (setting 'SHA224')`_.  
  And on dev  _`TypeError: Cannot read properties of undefined (reading 'stack')`_ 

I recommend sticking with version `v15.1.7` until a solution is found, either on Next.js' side or Intlayer's.

**Comment by aymericzip** [comment]
Hi @CarrettaRiccardo,

The issues should now be fixed:

-> Stack error: Resolved in next-intlayer `v5.2.9`.
-> SHA-224 error: Fixed in Next.js `v15.2.2-canary.3`.

### Recommendation
I suggest sticking with Next.js `v15.1.7` until the stable release of `v15.2.2`.

### References
[vercel/next.js#76817](https://github.com/vercel/next.js/issues/76817)
[vercel/next.js#76395 (comment)](https://github.com/vercel/next.js/issues/76395#issuecomment-2711261866)

**Comment by aymericzip** [comment]
### [update]

New Next.js `v15.2.2` has been tested and appears to be working.

**Comment by ryantbrown** [comment]
@aymericzip Are you 100% sure this is working? If so, that means its not a duplicate of https://github.com/vercel/next.js/issues/76395 as I can confirm that issue still exists on all 15.2.* versions, including canaries

**Comment by aymericzip** [comment]
@ryantbrown I'm sorry to hear that you're also experiencing this issue.  

First, are you using `intlayer`, or could the error be coming from another package, such as `next-mdx-remote-client` or `next-seo`?  

I tested `intlayer`, and it seems to be working fine since version `v5.2.9` with Next.js `>15.2.2-canary.3`. You can try this template to verify:  
[Next.js 15 + Intlayer Template](https://github.com/aymericzip/next-15-intlayer-template)

On the `next-intlayer` side, please ensure that the `react-intlayer` package version is `>5.2.9`:  
```sh
npm list react-intlayer --depth 1
```  
If it's outdated, try removing `node_modules` and `package-lock.json`, then reinstalling dependencies to ensure the correct `react-intlayer` version is used

Let me know if you're still encountering issues!

**Comment by ryantbrown** [comment]
No I am not using `intlayer` - I just noticed that this issue was marked as a duplicate of https://github.com/vercel/next.js/issues/76395

They may be related, but they are not duplicates because 76395 is still happening.

**Comment by ryantbrown** [comment]
I recognize this isn't the best place for this conversation, just wanted to be sure it was resolved on your end.

**Comment by aymericzip** [comment]
@ryantbrown 

This issue include three different bugs. However, the stack error specifically appears to be a duplicate of [#76395](https://github.com/vercel/next.js/issues/76395).  

I'm not sure why this error started occurring. It would be great to get some insights from the Next.js team. To investigate, I iterated by gradually removing parts of the code to pinpoint where the issue originated 

I shared how I fixed it for `intlayer` in the discussion on #76395, hoping it might help others. However, I'm not familiar enough with `next-mdx`, `next-seo`, or `content-layer` to provide a solution for those cases. there could be multiple causes triggering this error.  

Let me know if I can help you regarding something

**Comment by monolithed** [comment]
@aymericzip, I've been testing it with Next.js 16 and the documentation confused me as well.

Since async components in Next.js can only be server components — what's the recommended pattern for using both providers correctly?


```tsx
// src/app/layout.tsx

import type {NextLayoutIntlayer} from 'next-intlayer';
import {generateStaticParams} from 'next-intlayer';

const RootLayout: NextLayoutIntlayer = async ({children}) => children;

export const dynamic = 'force-static';

export {generateStaticParams};
export default RootLayout;
```

```tsx
// src/app/[locale]/layout.tsx

import type React from 'react';
import type {NextLayoutIntlayer} from 'next-intlayer';
import {getHTMLTextDir} from 'intlayer';
import {AntdRegistry} from '@ant-design/nextjs-registry';
import {IntlayerServerProvider} from 'next-intlayer/server';
import {IntlayerClientProvider} from 'next-intlayer';

import {inter} from '#/app/fonts.ts';
import {generateStaticParams} from '#/app/layout.ts';

import './globals.css';

const RootLayout: NextLayoutIntlayer = async ({children, params}) => {
    const {locale} = await params;
    const direction = getHTMLTextDir(locale);

    return (
        <html lang={locale} dir={direction}>
            <body className={inter.className}>
                <IntlayerServerProvider locale={locale}>
                    <IntlayerClientProvider locale={locale}>
                        <AntdRegistry>
                            {children}
                        </AntdRegistry>
                    </IntlayerClientProvider>
                </IntlayerServerProvider>
            </body>
        </html>
    )
};

export const dynamic = 'force-static';

export default RootLayout;
export {generateStaticParams};
```


```tsx
// src/app/[locale]/page.tsx
import type {ResolvingMetadata, Metadata} from 'next';

import {getMetadata, type Props} from '#/app/metadata.ts';
import {Namespaces} from '#/app/namespaces.ts';

import Page from '#/app/[locale]/index/index.tsx';

const generateMetadata = async (props: Props, parent: ResolvingMetadata): Promise<Metadata> => {
    return getMetadata(Namespaces.INDEX, props, parent);
};

export {generateMetadata};
export default Page;
```

```tsx
// src/app/[locale]/index/index.tsx
'use client';

import React from 'react';

const Index: React.FunctionComponent = () => <div> client </div>;

export default Index;
```

Should `IntlayerServerProvider` and `IntlayerClientProvider` be placed in the same layout (RootLayout)?

**Comment by aymericzip** [comment]
Hey @monolithed 

Thanks for reporting, I will try clarify the doc

In short : 
`ClientProvider` -> `src/app/[locale]/layout.tsx `
`ServerProvider`  -> `src/app/[locale]/page.tsx` (and any other pages)


Extracted from doc :

---

- **`IntlayerClientProvider`** is used to provide the locale to client-side components. It can be placed in any parent component, including the layout. However, placing it in a layout is recommended because Next.js shares layout code across pages, making it more efficient. By using `IntlayerClientProvider` in the layout, you avoid reinitializing it for every page, improving performance and maintaining a consistent localization context throughout your application.
- **`IntlayerServerProvider`** is used to provide the locale to the server children. It cannot be set set in the layout.

  > Layout and page cannot share a common server context because the server context system is based on a per-request data store (via [React's cache](https://react.dev/reference/react/cache) mechanism), causing each "context" to be re-created for different segments of the application. Placing the provider in a shared layout would break this isolation, preventing the correct propagation of the server context values to your server components.

**Comment by aymericzip** [comment]
I updated the docs @monolithed
