### ISSUE TITLE
How do I customize an exception page like a 404?

### ISSUE THREAD

**Issue by mutou981** [aymericzip/intlayer#343]
I'm using the tanstack start framework, and after setting '{-$locale}' at the moment, unknown URLs will also access the homepage successfully, and I need it to jump to the 404 page correctly.

**Comment by aymericzip** [comment]
Good point @mutou981 , thanks for asking 

I updated the template to demo it https://github.com/aymericzip/intlayer-tanstack-start-template/blob/main/src/routes/%7B-%24locale%7D/route.tsx



> Note: the behavior of tanstack router regarding not found pages is still a bit weird from by point of vue, there is multiple issue open on that topic 

 Code :

```tsx
import {
  createFileRoute,
  HeadContent,
  Outlet,
  redirect,
  Scripts,
} from '@tanstack/react-router';
import { configuration } from 'intlayer';
import Header from '@/components/Header';
import { NotFoundComponent } from './404';

const queryClient = new QueryClient();

const { locales, defaultLocale } = configuration.internationalization;

export const Route = createFileRoute('/{-$locale}')({
  beforeLoad: async ({ params }) => {
    // Get locale from route params (not from server headers, as beforeLoad runs on both client and server)
    const locale = params.locale;

    // If no locale provided (optional param), it's valid (will use default)
    // In prefix-all mode, the locale is required to be a valid locale
    const { localePrefix } = getPrefix(localeParam ?? defaultLocale, { mode });
    if (localePrefix === localeParam && localeParam === undefined) return;

    // Check if the provided locale is valid
    const isValidLocale = locales.some((localeEl) => localeEl === locale);

    if (!isValidLocale) {
      throw redirect({
        to: '/{-$locale}/404',
        params: { locale: undefined }, // Locale param is undefined in routing.mode = 'prefix-no-default', but can be changed by defaultLocale in routing.mode = 'prefix-all'
      });
    }
  },
  component: RouteComponent,
  notFoundComponent: NotFoundComponent,
});

function RouteComponent() {
  const { locale } = Route.useParams();

  useI18nHTMLAttributes();

  return (
    <html lang={locale ?? defaultLocale}>
      <head>
        <HeadContent />
      </head>
      <body>
        <Header />
         <Outlet />
        <Scripts />
      </body>
    </html>
  );
}
```

```tsx
import { createFileRoute, HeadContent, Scripts } from '@tanstack/react-router';
import { useIntlayer, useLocale } from 'react-intlayer';

import { LocalizedLink } from '@/components/localized-link';

export const Route = createFileRoute('/{-$locale}/404')({
  component: NotFoundComponent,
});

export function NotFoundComponent() {
  const { locale } = Route.useParams();
  const { defaultLocale } = useLocale();
  const { title, subtitle, backHome, lostMessage } = useIntlayer('not-found');

  return (
    <html lang={locale ?? defaultLocale}>
      <head>
        <HeadContent />
      </head>
      <body>
        <div>
          404
        </div>
        <Scripts />
      </body>
    </html>
  );
}

```

**Comment by mutou981** [comment]
thx, @aymericzip I test that there is a special case to deal with 'http://localhost:3001/en123' - resp 'Cannot GET /en123'

**Comment by aymericzip** [comment]
you're right @mutou981 

I pushed a new change on the template, and introduced a new `validatePrefix` helper, if you want to have a look

See https://intlayer.org/doc/environment/tanstack-start#step-14-manage-not-found-pages-optional

**Comment by mutou981** [comment]
Haha, thank you! I tested online and it was OK, but local development of '/en123' is still a problem. I don't know if you have encountered such a problem?

**Comment by aymericzip** [comment]
hey @mutou981 

Can you share your `intlayer.config.ts` ?

`/en123` keep returning `Cannot GET /en123`?

**Comment by aymericzip** [comment]
is setting up `src/routes/{-$locale}/$.tsx` helps ?

**Comment by mutou981** [comment]
https://github.com/hehehai/tiny-svg/blob/main/apps/web/intlayer.config.ts

**Comment by mutou981** [comment]
> is setting up `src/routes/{-$locale}/$.tsx` helps ?

yep

**Comment by mutou981** [comment]
@aymericzip Where do you look normal?

**Comment by aymericzip** [comment]
hey @mutou981 , sorry for my late reply 

you're right, thanks again for reporting

actually that error is related to the tanstack set up, I cant do much better for now, but I will see with the tanstack team if we can have a better implementation, that could remove that ugly `${-locale}`

**Comment by aymericzip** [comment]
your set up looks fine btw

**Comment by aymericzip** [comment]
hey @mutou981,

I'm closing this issue because no move from the tanstack start side
